apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-gitops
  namespace: argocd
spec:
  project: python-gitops
  source:
    repoURL: https://github.com/ydvsailendar/python-gitops
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: python-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
