apiVersion: apps/v1
type: Deployment
metadata:
  name: python-gitops
	namespace: python-gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-gitops
  template:
    metadata:
      labels:
        app: python-gitops
    spec:
      containers:
        - name: python-gitops
          image: yadavshailendra0905/python-gitops:v1.0.0
          ports:
            - containerPort: 5000
          resources:
						requests:
							cpu: "100m"
							memory: "128Mi"
						limits:
							cpu: "500m"
							memory: "256Mi"
